CREATE USER 'iblog'@'localhost' IDENTIFIED BY '123456';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `iblog`.* TO 'iblog'@'localhost';

GRANT GRANT OPTION ON `iblog`.* TO 'iblog'@'localhost';